Modul4 task1
Dzoter/readme_rara pull request #9
Opened 2023-08-21 13:16 UTC by AleksandrVasilenok

Подготовка

Создайте новый файл в корне проекта с именем schema.sql.

В этом файле напишите весь SQL-код для создания схемы БД вашего проекта.

Требования:

весь SQL-код должен без ошибок выполняться на MySQL 5.7;
в каждой таблице должен быть первичный ключ.
План работы

Сперва напишите SQL-код для создания новой базы данных с именем вашего проекта.

Напишите SQL-код для создания всех необходимых таблиц.

Добавьте уникальные индексы полям, где должны быть только уникальные значения.

Добавьте обычные индексы полям, по которым будет происходить поиск.

Основные сущности

**Поля:**
дата регистрации: дата и время, когда этот пользователь завёл аккаунт;
email;
логин;
пароль: хэшированный пароль пользователя;
аватар: ссылка на загруженный аватар пользователя;

**Пост**
Состоит из заголовка и содержимого. Набор полей, которые будут заполнены, зависит от выбранного типа.
**Поля**:
дата создания: дата и время, когда этот пост был создан пользователем;
заголовок: задаётся пользователем;
текстовое содержимое: задаётся пользователем;
автор цитаты: задаётся пользователем;
изображение: ссылка на сохранённый файл изображения;
видео: ссылка на видео с youtube;
ссылка: ссылка на сайт, задаётся пользователем;
число просмотров.
**Связи**:
автор: пользователь, создавший пост;
тип контента: тип контента, к которому относится пост;
хештеги: связь вида «многие-ко-многим» с сущностью «хештег».

**Комментарий**
Текстовый комментарий, оставленный к одному из постов.
**Поля**:
дата создания: дата и время создания комментария;
содержимое: задается пользователем.
**Связи**:
автор: пользователь, создавший пост;
пост: пост, к которому добавлен комментарий.
 
**Лайк**
Эта сущность состоит только из связей и не имеет собственных полей.
**Связи:**
пользователь: кто оставил этот лайк;
пост: какой пост лайкнули.

**Подписка**
Эта сущность состоит только из связей и не имеет собственных полей. Сущность создается, когда пользователь подписывается на другого пользователя.
**Связи:**
автор: пользователь, который подписался;
подписка: пользователь, на которого подписались.

**Сообщение**
Одно сообщение из внутренней переписки пользователей на сайте
**Поля:**
дата создания: дата и время, когда это сообщение написали;
содержимое: задаётся пользователем.
**Связи**:
отправитель: пользователь, отправивший сообщение;
получатель: пользователь, которому отправили сообщение.

**Хештег**
Один из используемых хештегов на сайте. Сущность состоит только из названия хештега.

**Тип контента**
Один из пяти предопределенных типов контента.

**Поля:**
название (Текст, Цитата, Картинка, Видео, Ссылка);
имя класса для иконки (photo, video, text, quote, link);

2023-08-21 13:33 UTC, Dzoter requested changes

2023-08-21 13:33 UTC, Dzoter commented on schema.sql
> +create DATABASE Readme
назови по особенному, т.к. у меня уже есть бд Redme в mysql. Например Readme_rara

2023-08-21 13:33 UTC, Dzoter commented on schema.sql
> +  UserId int AUTO_INCREMENT PRIMARY KEY,
просто id, и так понятно чей он ведь таблица User. сделай так же со всеми остальными таблицами

2023-08-21 13:33 UTC, Dzoter commented on schema.sql
> +  createPostDate  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
поле created_at

2023-08-21 13:33 UTC, Dzoter commented on schema.sql
> +create table PostsHashtag
Названия табиц так же через _

2023-08-21 13:35 UTC, Dzoter commented on schema.sql
> +  pathPicture varchar(255),
таблицы и колонки в таблицах

2023-08-21 13:37 UTC, AleksandrVasilenok commented on schema.sql
> +create DATABASE Readme
исправил.

2023-08-21 13:40 UTC, AleksandrVasilenok commented on schema.sql
> +  UserId int AUTO_INCREMENT PRIMARY KEY,
исправил.

2023-08-21 14:42 UTC, Dzoter requested changes

2023-08-21 14:42 UTC, Dzoter commented on schema.sql
> +create table Post
мн число

2023-08-21 14:42 UTC, Dzoter commented on schema.sql
> +create table Hashtag
мн число

2023-08-23 20:05 UTC, Dzoter approved these changes

2023-08-23 20:05 UTC, merged